# Generated by Django 5.2.5 on 2025-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
